travis:
  secure:
    BINSTAR_TOKEN: odSjEaLAkLFlPF3XLX58xmu8gG+mtcPX0uatIwPQOIE6ndBvIjvQZq7eUPBoW0zY5AwhtUpg6RJ1CdiRIK1LE7JuYDs8+PguDJ1ocmV2Eoww089U7KlO0DDL5Sdmy/mLASgo24eVUkS6tmPs2MONozJHMDndkUWFZFlIq2tajdM4jd8Fp1VWM17h14AfZrZ9u2thDZArSQZ2p4MlVZZD0Rb7ybUfxwpp5ssylPMBuedx05QyR0WYfwucmkeLgDaXU8H+GUjoFrjRZNsreHKLiT1NgB8cJ03yVD4k8Waoq5FnnGZ/zqpe0xDsGIOqjT80AU7Q6hVsdkio8qpJSBDyVp+jjt+gMue9EFqaAZYIiPlP2MEQKDHQNXHmPpsRficY3/SDqSeOSvKYdK42hXgrDYEZ0WVCDWxpfrF170DEgTbIMBFwdBAvf/SZL3d8b1hJVw7+VXEbJLboqyhwert7tFnjlWDnnmljygjUTeACQMPUBGPyKiSm2T/I8A5RuTpIUluNm5KnefJ6FlNsqdNQ55jUFcy5H/ZfBlLgO/qMUEonBWgWkyXWzY6/KVX7UDbo+vLRQH6uYM2mb0BtYG7S4t3maCd5YZwm1SiRopgczrLlC2lEUAsMiARu5vci6DOUQpAQDwgB/KRoF2Px/3zOVXv35ySQ/XpWaVy9Msj0+0c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
